#!/bin/bash
# =============================================================================
# JARVIS Distributed System - Interactive Setup Script
# =============================================================================
# This script sets up JARVIS as either a server or client
# Handles: dependencies, certificates, configuration, and systemd services

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Default values
CERT_DIR="certs"
CONFIG_DIR="config"
DATA_DIR="data"

# =============================================================================
# Helper Functions
# =============================================================================

print_banner() {
    echo -e "${CYAN}"
    echo "     ██╗ █████╗ ██████╗ ██╗   ██╗██╗███████╗"
    echo "     ██║██╔══██╗██╔══██╗██║   ██║██║██╔════╝"
    echo "     ██║███████║██████╔╝██║   ██║██║███████╗"
    echo "██   ██║██╔══██║██╔══██╗╚██╗ ██╔╝██║╚════██║"
    echo "╚█████╔╝██║  ██║██║  ██║ ╚████╔╝ ██║███████║"
    echo " ╚════╝ ╚═╝  ╚═╝╚═╝  ╚═╝  ╚═══╝  ╚═╝╚══════╝"
    echo -e "${NC}"
    echo -e "${BLUE}Distributed AI Assistant - Setup${NC}"
    echo ""
}

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_command() {
    if command -v "$1" &> /dev/null; then
        return 0
    else
        return 1
    fi
}

# =============================================================================
# Dependency Installation
# =============================================================================

install_system_deps() {
    log_info "Checking system dependencies..."
    
    # Detect package manager
    if check_command apt-get; then
        PKG_MANAGER="apt"
        INSTALL_CMD="sudo apt-get install -y"
    elif check_command pacman; then
        PKG_MANAGER="pacman"
        INSTALL_CMD="sudo pacman -S --noconfirm"
    elif check_command dnf; then
        PKG_MANAGER="dnf"
        INSTALL_CMD="sudo dnf install -y"
    else
        log_warn "Unknown package manager. Please install dependencies manually."
        return 1
    fi
    
    log_info "Using package manager: $PKG_MANAGER"
    
    # Common packages
    PACKAGES="python3 python3-pip python3-venv portaudio19-dev espeak"
    
    if [ "$PKG_MANAGER" = "pacman" ]; then
        PACKAGES="python python-pip portaudio espeak-ng"
    elif [ "$PKG_MANAGER" = "dnf" ]; then
        PACKAGES="python3 python3-pip portaudio-devel espeak-ng"
    fi
    
    echo -e "${YELLOW}Installing: $PACKAGES${NC}"
    $INSTALL_CMD $PACKAGES || log_warn "Some packages may have failed to install"
}

install_python_deps() {
    log_info "Setting up Python virtual environment..."
    
    # Create venv if not exists
    if [ ! -d "venv" ]; then
        python3 -m venv venv
    fi
    
    # Activate venv
    source venv/bin/activate
    
    # Upgrade pip
    pip install --upgrade pip
    
    # Install requirements
    log_info "Installing Python dependencies..."
    pip install -r requirements.txt
    
    # Install additional packages for distributed features
    log_info "Installing distributed system dependencies..."
    pip install grpcio grpcio-tools cryptography paho-mqtt zeroconf aiohttp
}

# =============================================================================
# Certificate Generation
# =============================================================================

generate_certificates() {
    log_info "Setting up certificates..."
    
    source venv/bin/activate
    
    # Initialize CA
    python -c "
from jarvis.security.pki import CertificateAuthority
ca = CertificateAuthority('$CERT_DIR')
if ca.initialize():
    print('CA initialized')
    if '$MODE' == 'server':
        key, cert = ca.generate_server_cert(
            hostname='$HOSTNAME',
            ip_addresses=['$SERVER_IP', '127.0.0.1', '0.0.0.0'],
            dns_names=['$HOSTNAME', 'localhost', 'jarvis-server'],
        )
        if key and cert:
            print(f'Server cert: {cert}')
    else:
        key, cert = ca.generate_client_cert(
            client_id='$CLIENT_ID',
            hostname='$HOSTNAME',
        )
        if key and cert:
            print(f'Client cert: {cert}')
"
}

# =============================================================================
# Configuration
# =============================================================================

create_config() {
    log_info "Creating configuration..."
    
    mkdir -p "$CONFIG_DIR"
    
    if [ "$MODE" = "server" ]; then
        cat > "$CONFIG_DIR/user.yaml" << EOF
# JARVIS Server Configuration
# Generated by setup.sh on $(date)

core:
  name: "Jarvis Server"

network:
  mode: "server"
  server_host: "0.0.0.0"
  server_port: $SERVER_PORT
  
  tls:
    enabled: $TLS_ENABLED
    cert_path: "$CERT_DIR/server.crt"
    key_path: "$CERT_DIR/server.key"
    ca_path: "$CERT_DIR/ca.crt"
    require_client_cert: $REQUIRE_CLIENT_CERT
  
  discovery:
    enabled: true
    method: "zeroconf"
  
  iot:
    mqtt:
      enabled: $MQTT_ENABLED
      host: "localhost"
      port: 1883

autonomous:
  task_planning: true
  pattern_learning: true
  proactive_suggestions: true

web:
  enabled: true
  host: "0.0.0.0"
  port: 8000

ai:
  llm:
    provider: "${AI_PROVIDER:-ollama}"
    ollama_model: "${OLLAMA_MODEL:-llama3.2}"
    ollama_host: "http://localhost:11434"
EOF
    else
        cat > "$CONFIG_DIR/user.yaml" << EOF
# JARVIS Client Configuration
# Generated by setup.sh on $(date)

core:
  name: "Jarvis Client"

network:
  mode: "client"
  server_host: "$SERVER_HOST"
  server_port: $SERVER_PORT
  
  client:
    client_id: "$CLIENT_ID"
    auto_reconnect: true
    reconnect_delay: 5
  
  tls:
    enabled: $TLS_ENABLED
    cert_path: "$CERT_DIR/clients/$CLIENT_ID/client.crt"
    key_path: "$CERT_DIR/clients/$CLIENT_ID/client.key"
    ca_path: "$CERT_DIR/clients/$CLIENT_ID/ca.crt"

voice:
  enabled: true
  
  tts:
    engine: "espeak"
    rate: 175
EOF
    fi
    
    log_info "Configuration saved to $CONFIG_DIR/user.yaml"
}

# =============================================================================
# Systemd Service
# =============================================================================

create_systemd_service() {
    log_info "Creating systemd service..."
    
    SERVICE_NAME="jarvis-$MODE"
    SERVICE_FILE="/etc/systemd/system/$SERVICE_NAME.service"
    WORKING_DIR=$(pwd)
    
    if [ "$MODE" = "server" ]; then
        EXEC_START="$WORKING_DIR/venv/bin/python $WORKING_DIR/main.py --mode server"
    else
        EXEC_START="$WORKING_DIR/venv/bin/python $WORKING_DIR/main.py --mode client --server-host $SERVER_HOST --server-port $SERVER_PORT"
    fi
    
    sudo tee "$SERVICE_FILE" > /dev/null << EOF
[Unit]
Description=JARVIS AI Assistant ($MODE)
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$WORKING_DIR
Environment="PATH=$WORKING_DIR/venv/bin:/usr/local/bin:/usr/bin:/bin"
ExecStart=$EXEC_START
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

    sudo systemctl daemon-reload
    sudo systemctl enable "$SERVICE_NAME"
    
    log_info "Systemd service created: $SERVICE_NAME"
    echo "  Start: sudo systemctl start $SERVICE_NAME"
    echo "  Status: sudo systemctl status $SERVICE_NAME"
    echo "  Logs: journalctl -u $SERVICE_NAME -f"
}

# =============================================================================
# Firewall Configuration
# =============================================================================

configure_firewall() {
    log_info "Configuring firewall..."
    
    if check_command ufw; then
        # Ubuntu/Debian UFW
        sudo ufw allow $SERVER_PORT/tcp comment "JARVIS gRPC"
        sudo ufw allow 8000/tcp comment "JARVIS Web Dashboard"
        if [ "$MQTT_ENABLED" = "true" ]; then
            sudo ufw allow 1883/tcp comment "MQTT"
        fi
        log_info "UFW rules added"
    elif check_command firewall-cmd; then
        # Fedora/RHEL firewalld
        sudo firewall-cmd --add-port=$SERVER_PORT/tcp --permanent
        sudo firewall-cmd --add-port=8000/tcp --permanent
        if [ "$MQTT_ENABLED" = "true" ]; then
            sudo firewall-cmd --add-port=1883/tcp --permanent
        fi
        sudo firewall-cmd --reload
        log_info "Firewalld rules added"
    else
        log_warn "No supported firewall detected. Please open ports manually:"
        echo "  - $SERVER_PORT/tcp (gRPC)"
        echo "  - 8000/tcp (Web Dashboard)"
    fi
}

# =============================================================================
# Interactive Setup
# =============================================================================

interactive_setup() {
    print_banner
    
    echo "This script will set up JARVIS on your system."
    echo ""
    
    # Mode selection
    echo "Select installation mode:"
    echo "  1) Server - Central AI brain (run on main server/Raspberry Pi)"
    echo "  2) Client - Controlled endpoint (run on PCs)"
    echo ""
    read -p "Enter choice [1/2]: " MODE_CHOICE
    
    case $MODE_CHOICE in
        1) MODE="server" ;;
        2) MODE="client" ;;
        *) 
            log_error "Invalid choice"
            exit 1
            ;;
    esac
    
    # Get hostname
    HOSTNAME=$(hostname)
    
    if [ "$MODE" = "server" ]; then
        # Server setup
        read -p "Server port [50051]: " SERVER_PORT
        SERVER_PORT=${SERVER_PORT:-50051}
        
        # Get server IP
        SERVER_IP=$(hostname -I | awk '{print $1}')
        read -p "Server IP address [$SERVER_IP]: " INPUT_IP
        SERVER_IP=${INPUT_IP:-$SERVER_IP}
        
        read -p "Enable TLS/mTLS? [y/N]: " TLS_CHOICE
        TLS_ENABLED=$([ "$TLS_CHOICE" = "y" ] || [ "$TLS_CHOICE" = "Y" ] && echo "true" || echo "false")
        
        REQUIRE_CLIENT_CERT="false"
        if [ "$TLS_ENABLED" = "true" ]; then
            read -p "Require client certificates (mTLS)? [y/N]: " MTLS_CHOICE
            REQUIRE_CLIENT_CERT=$([ "$MTLS_CHOICE" = "y" ] || [ "$MTLS_CHOICE" = "Y" ] && echo "true" || echo "false")
        fi
        
        read -p "Enable MQTT for IoT devices? [y/N]: " MQTT_CHOICE
        MQTT_ENABLED=$([ "$MQTT_CHOICE" = "y" ] || [ "$MQTT_CHOICE" = "Y" ] && echo "true" || echo "false")
        
        read -p "AI Provider [ollama]: " AI_PROVIDER
        AI_PROVIDER=${AI_PROVIDER:-ollama}
        
        if [ "$AI_PROVIDER" = "ollama" ]; then
            read -p "Ollama model [llama3.2]: " OLLAMA_MODEL
            OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.2}
        fi
        
    else
        # Client setup
        read -p "Server hostname/IP: " SERVER_HOST
        if [ -z "$SERVER_HOST" ]; then
            log_error "Server hostname is required"
            exit 1
        fi
        
        read -p "Server port [50051]: " SERVER_PORT
        SERVER_PORT=${SERVER_PORT:-50051}
        
        # Generate client ID
        CLIENT_ID=$(hostname)-$(date +%s | md5sum | head -c 8)
        read -p "Client ID [$CLIENT_ID]: " INPUT_ID
        CLIENT_ID=${INPUT_ID:-$CLIENT_ID}
        
        read -p "Enable TLS? [y/N]: " TLS_CHOICE
        TLS_ENABLED=$([ "$TLS_CHOICE" = "y" ] || [ "$TLS_CHOICE" = "Y" ] && echo "true" || echo "false")
    fi
    
    # Install dependencies?
    read -p "Install system dependencies? [Y/n]: " DEPS_CHOICE
    INSTALL_DEPS=$([ "$DEPS_CHOICE" = "n" ] || [ "$DEPS_CHOICE" = "N" ] && echo "false" || echo "true")
    
    # Create systemd service?
    read -p "Create systemd service for auto-start? [Y/n]: " SERVICE_CHOICE
    CREATE_SERVICE=$([ "$SERVICE_CHOICE" = "n" ] || [ "$SERVICE_CHOICE" = "N" ] && echo "false" || echo "true")
    
    # Configure firewall?
    if [ "$MODE" = "server" ]; then
        read -p "Configure firewall? [Y/n]: " FW_CHOICE
        CONFIGURE_FW=$([ "$FW_CHOICE" = "n" ] || [ "$FW_CHOICE" = "N" ] && echo "false" || echo "true")
    else
        CONFIGURE_FW="false"
    fi
    
    echo ""
    log_info "Configuration Summary:"
    echo "  Mode: $MODE"
    echo "  Hostname: $HOSTNAME"
    if [ "$MODE" = "server" ]; then
        echo "  Server IP: $SERVER_IP"
        echo "  Server Port: $SERVER_PORT"
        echo "  TLS: $TLS_ENABLED"
        echo "  mTLS: $REQUIRE_CLIENT_CERT"
        echo "  MQTT: $MQTT_ENABLED"
        echo "  AI: $AI_PROVIDER"
    else
        echo "  Server: $SERVER_HOST:$SERVER_PORT"
        echo "  Client ID: $CLIENT_ID"
        echo "  TLS: $TLS_ENABLED"
    fi
    echo ""
    
    read -p "Proceed with installation? [Y/n]: " CONFIRM
    if [ "$CONFIRM" = "n" ] || [ "$CONFIRM" = "N" ]; then
        log_info "Installation cancelled"
        exit 0
    fi
    
    # Execute setup
    echo ""
    
    if [ "$INSTALL_DEPS" = "true" ]; then
        install_system_deps
    fi
    
    install_python_deps
    
    if [ "$TLS_ENABLED" = "true" ]; then
        generate_certificates
    fi
    
    create_config
    
    if [ "$CREATE_SERVICE" = "true" ]; then
        create_systemd_service
    fi
    
    if [ "$CONFIGURE_FW" = "true" ]; then
        configure_firewall
    fi
    
    echo ""
    echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}           JARVIS Setup Complete!                       ${NC}"
    echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
    echo ""
    
    if [ "$MODE" = "server" ]; then
        echo "To start JARVIS server manually:"
        echo "  source venv/bin/activate"
        echo "  python main.py --mode server"
        echo ""
        echo "Web dashboard will be available at:"
        echo "  http://$SERVER_IP:8000"
        echo ""
        echo "Clients can connect to:"
        echo "  $SERVER_IP:$SERVER_PORT"
    else
        echo "To start JARVIS client manually:"
        echo "  source venv/bin/activate"
        echo "  python main.py --mode client --server-host $SERVER_HOST"
    fi
    
    if [ "$CREATE_SERVICE" = "true" ]; then
        echo ""
        echo "Or use systemd:"
        echo "  sudo systemctl start jarvis-$MODE"
    fi
}

# =============================================================================
# Main
# =============================================================================

# Check for --help or -h
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    echo "JARVIS Setup Script"
    echo ""
    echo "Usage: ./setup.sh [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --server           Set up as server"
    echo "  --client           Set up as client"
    echo "  --server-host IP   Server IP (for client)"
    echo "  --interactive      Interactive setup (default)"
    echo "  --help             Show this help"
    exit 0
fi

# Run interactive setup
interactive_setup
